import streamlit as st
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()

st.title("LAWS90286 - D1")

# Store important variables in a session_state
if "name" not in st.session_state: 
    st.session_state.name = ""
if "button_value" not in st.session_state:
    st.session_state.button_value = False
if "option" not in st.session_state:
    st.session_state.option = ""

# 1. Ask user to enter name
st.header("Part 1 - Get name")
st.session_state.name = st.text_input("What's your name?")

# 2. If user enters name and clicks button, display welcome message to the user
st.header("Part 2 - Click button")
st.session_state.button_value = st.button("Click me")

st.header("Part 3 - Display Name (Hardcoded)")
if st.session_state.name != "" and st.session_state.button_value == True:
    st.write(f"Hello,", st.session_state.name)

# 3. Welcome message should be generated by GPT 4o
st.header("Part 3 - Display Name (Generated)")
client = OpenAI()

st.header("Part 4 - Greet the user")
response = client.responses.create(
    model="gpt-4o",
    input=f"Greet {name} and make them welcome"
)

st.write(response.output_text)

# 4. User should be able to select different personas to be welcomed by
st.header("Part 5 - Display Welcome based on Persona")

st.session_state.option = st.selectbox(
    "What persona?",
    ("Shark", "Cow", "Formula 1 Driver")
)

response = client.responses.create(
    model="gpt-4o",
    instructions=f"You must respond as if you are a: {st.session_state.option}",
    input=f"Greet {st.session_state.name} and make them welcome"
)

st.write(response.output_text)