import streamlit as st
from openai import openai
from dotenv import load_dotenv

load_dotenv()

# 1. Ask user to enter name
# 2. If user enters name and clicks button, display welcome message 
# 3. Welcome message should be generated by GPT 4o
# 4. 